// ============================
// POCHIBAG — Product Catalog
// Perfumes · Handbags · Jewellery
// ============================

// Shorthand for WhatsApp image folder
const WA = "WhatsApp Unknown 2026-04-06 at 09.54.38/";

const PRODUCTS = [

  // ── PERFUMES ──
  {
    id: 1,
    name: "Aquatic Kiss",
    category: "Perfumes",
    subcategory: "Eau de Parfum",
    price: { "100ml": 1200, "50ml": 900, "24ml": 500 },
    oldPrice: null,
    badge: "bestseller",
    rating: "4.9",
    reviews: 824,
    sizes: ["24ml", "50ml", "100ml"],
    desc: "A fresh, luminous aquatic fragrance in our signature Pochi bottle. Evokes sea breeze and white flowers — light yet unforgettable, a scent that stays with you all day.",
    notes: { top: "Sea Salt, Green Citrus", heart: "White Jasmine, Aquatic Accord", base: "Driftwood, White Musk, Ambergris" },
    img: "Perfume image.png",
    images: ["Perfume image.png", "Perfume image 2.png"]
  },
  {
    id: 2,
    name: "Secret Garden",
    category: "Perfumes",
    subcategory: "Eau de Parfum",
    price: { "100ml": 1200, "50ml": 900, "24ml": 500 },
    oldPrice: null,
    badge: "new",
    rating: "4.8",
    reviews: 312,
    sizes: ["24ml", "50ml", "100ml"],
    desc: "Our most-loved fragrance. Step into a hidden garden at dusk in our Dior-inspired bottle. Dewy green leaves give way to a heart of rare florals and warm amber — intimate, mysterious, beautifully feminine.",
    notes: { top: "Green Leaves, Bergamot", heart: "Peony, Iris, Rose", base: "Amber, Sandalwood, White Musk" },
    img: "Perfume image 2.png",
    images: ["Perfume image 2.png", "Perfume image.png"]
  },
  {
    id: 3,
    name: "Noir Santal Mystère",
    category: "Perfumes",
    subcategory: "Eau de Parfum",
    price: { "100ml": 1200, "50ml": 900, "24ml": 500 },
    oldPrice: null,
    badge: "sale",
    rating: "5.0",
    reviews: 561,
    sizes: ["50ml", "100ml"],
    desc: "A smoky, intimate blend of rare sandalwood and black pepper in an elegant dark bottle. Mysterious, powerful, and deeply seductive.",
    notes: { top: "Black Pepper, Cardamom", heart: "Sandalwood, Patchouli", base: "Smoke, Leather, Benzoin" },
    img: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80"
  },
  {
    id: 4,
    name: "White Gardenia Dreams",
    category: "Perfumes",
    subcategory: "Eau de Toilette",
    price: { "100ml": 1200, "50ml": 900, "24ml": 500 },
    oldPrice: null,
    badge: "new",
    rating: "4.7",
    reviews: 198,
    sizes: ["24ml", "50ml", "100ml"],
    desc: "Fresh and luminous. This floral masterpiece captures morning gardenia in full bloom, wrapped in clean citrus and soft woods. Your everyday elegance.",
    notes: { top: "Lemon, Green Leaves", heart: "Gardenia, Jasmine, Lily", base: "White Musk, Sandalwood" },
    img: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80"
  },
  {
    id: 5,
    name: "Amber Rose Royale",
    category: "Perfumes",
    subcategory: "Extrait de Parfum",
    price: { "100ml": 1200, "50ml": 900, "24ml": 500 },
    oldPrice: null,
    badge: "exclusive",
    rating: "5.0",
    reviews: 143,
    sizes: ["24ml", "50ml"],
    desc: "Our most opulent fragrance. Layers of deep Bulgarian rose, warm amber, and precious resins create a regal scent. Available in our signature golden bottle.",
    notes: { top: "Pink Peppercorn, Aldehydes", heart: "Bulgarian Rose, Ylang-Ylang", base: "Amber Resin, Oud, Labdanum" },
    img: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80"
  },
  {
    id: 6,
    name: "Caramel Tobacco Luxe",
    category: "Perfumes",
    subcategory: "Eau de Parfum",
    price: { "100ml": 1200, "50ml": 900, "24ml": 500 },
    oldPrice: null,
    badge: "sale",
    rating: "4.8",
    reviews: 430,
    sizes: ["50ml", "100ml"],
    desc: "Sweet yet confident. A warm blend of golden caramel, dark tobacco leaves and creamy vanilla — bold meets irresistible. DM to order! 💬",
    notes: { top: "Bergamot, Black Currant", heart: "Tobacco, Caramel, Jasmine", base: "Vanilla, Sandalwood, Musk" },
    img: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80"
  },

  // ── HANDBAGS ──
  {
    id: 101,
    name: "Pochi Monogram Baguette",
    category: "Handbags",
    subcategory: "Shoulder Bags",
    price: 1299,
    oldPrice: null,
    badge: "bestseller",
    rating: "4.9",
    reviews: 672,
    sizes: ["One Size"],
    desc: "Our signature style. The iconic 'C' monogram print in premium faux leather, available in Brown, Black, Cream, White/Green and more. A must-have baguette bag for every wardrobe.",
    materials: "Premium faux leather with monogram embossing, gold-tone hardware, suede interior with zip pocket.",
    img: "Handbags.png",
    images: [
      "Handbags.png",
      WA + "WhatsApp Image 2026-04-06 at 03.13.00 (1).jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.01.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.01 (1).jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.02.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.02 (1).jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.02 (2).jpeg"
    ]
  },
  {
    id: 102,
    name: "Ivory & Green Structured Satchel",
    category: "Handbags",
    subcategory: "Crossbody Bags",
    price: 1299,
    oldPrice: null,
    badge: "new",
    rating: "4.8",
    reviews: 289,
    sizes: ["One Size"],
    desc: "A bold statement piece. Ivory structured body with a hunter green leather trim and our signature stag-head gold clasp hardware. Comes with a detachable chain strap.",
    materials: "Structured faux leather, antique gold hardware, fabric interior with two zip pockets.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.13.04 (1).jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.13.04 (1).jpeg",
      "handbag 1.png"
    ]
  },
  {
    id: 103,
    name: "Noir Quilted Chain Bag",
    category: "Handbags",
    subcategory: "Shoulder Bags",
    price: 1299,
    oldPrice: null,
    badge: "new",
    rating: "4.7",
    reviews: 154,
    sizes: ["One Size"],
    desc: "Channel timeless elegance with this Chanel-inspired quilted black bag. Diamond quilting, gold 'C' logo buckle, and a gold chain strap that doubles as a belt. Goes from day to night effortlessly.",
    materials: "Quilted PU leather, gold-finish logo hardware and chain strap, microfibre lining.",
    img: "handbag 2.png",
    images: [
      "handbag 2.png",
      WA + "WhatsApp Image 2026-04-06 at 03.13.01.jpeg"
    ]
  },
  {
    id: 104,
    name: "Beige Canvas Mini Tote",
    category: "Handbags",
    subcategory: "Tote Bags",
    price: 1299,
    oldPrice: null,
    badge: "sale",
    rating: "4.9",
    reviews: 507,
    sizes: ["One Size"],
    desc: "Casual luxury in warm beige. Woven canvas with leather handle trim and sleek silver bar-buckle closures. The perfect everyday companion that carries everything in style.",
    materials: "Woven canvas, genuine leather trim, silver-finish hardware, internal zip pocket.",
    img: "handbag 3.png",
    images: [
      "handbag 3.png",
      WA + "WhatsApp Image 2026-04-06 at 03.13.04.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.03.jpeg"
    ]
  },
  {
    id: 105,
    name: "Caramel Structured Top-Handle",
    category: "Handbags",
    subcategory: "Top Handle Bags",
    price: 1299,
    oldPrice: null,
    badge: null,
    rating: "4.6",
    reviews: 203,
    sizes: ["One Size"],
    desc: "Confidence in every carry. A rich caramel-toned structured bag with a distinctive braided top handle and elegant quatrefoil silver clasp. Classic meets contemporary.",
    materials: "Premium faux leather, silver-finish hardware, suede interior lining.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.13.03.jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.13.03.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.03 (1).jpeg"
    ]
  },
  {
    id: 106,
    name: "Noir Tassel Top-Handle",
    category: "Handbags",
    subcategory: "Top Handle Bags",
    price: 1299,
    oldPrice: null,
    badge: "hot",
    rating: "5.0",
    reviews: 389,
    sizes: ["One Size"],
    desc: "Drama, darling. A sleek black pebbled leather bag with statement tassel accents, a circular silver lock clasp, and a curved top handle. The bag that turns heads.",
    materials: "Pebbled PU leather, silver-finish lock hardware, fabric lining.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.13.05.jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.13.05.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.01.jpeg"
    ]
  },
  {
    id: 107,
    name: "Cream Scrunchie Crescent Bag",
    category: "Handbags",
    subcategory: "Shoulder Bags",
    price: 1299,
    oldPrice: null,
    badge: "new",
    rating: "4.8",
    reviews: 165,
    sizes: ["One Size"],
    desc: "Soft, playful, irresistible. This cream crescent shoulder bag features a gathered 'scrunchie' fabric handle and a sweet detachable mini coin pouch — effortlessly trendy.",
    materials: "Soft fabric body, gathered handle, detachable coin pouch, cotton lining.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.13.03 (1).jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.13.03 (1).jpeg"
    ]
  },

  // ── EVENING CLUTCHES ──
  {
    id: 108,
    name: "Crystal Silver Evening Clutch",
    category: "Handbags",
    subcategory: "Evening Clutches",
    price: 1299,
    oldPrice: null,
    badge: "new",
    rating: "4.9",
    reviews: 412,
    sizes: ["One Size"],
    desc: "Sparkle your night. A stunning grid-crystal silver clutch on a delicate pedestal handle. Perfect for galas, weddings, or any night you deserve to shine.",
    materials: "Crystal-encrusted frame, silver metal handle, satin interior.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.12.57.jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.12.57.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.13.00.jpeg"
    ]
  },
  {
    id: 109,
    name: "Gold Floral Crystal Clutch",
    category: "Handbags",
    subcategory: "Evening Clutches",
    price: 1299,
    oldPrice: null,
    badge: "bestseller",
    rating: "5.0",
    reviews: 538,
    sizes: ["One Size"],
    desc: "Pure opulence. A rectangular gold clutch adorned with crystal floral motifs and a dazzling diamond-cut clasp. The statement piece your evening wardrobe has been missing.",
    materials: "Gold-tone crystal embellishment, brass frame, satin lining.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.12.57 (1).jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.12.57 (1).jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.12.57.jpeg"
    ]
  },
  {
    id: 110,
    name: "Rose Gold Oval Glitter Clutch",
    category: "Handbags",
    subcategory: "Evening Clutches",
    price: 1299,
    oldPrice: null,
    badge: "new",
    rating: "4.8",
    reviews: 279,
    sizes: ["One Size"],
    desc: "Feminine and luminous. This rosy-pink oval clutch shimmers with glitter finish and an arch gold handle. Compact yet complete — enough room for your essentials and all the magic.",
    materials: "Glitter fabric, gold-tone arch handle, interior slip pocket.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.12.59.jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.12.59.jpeg"
    ]
  },
  {
    id: 111,
    name: "Silver Chevron Minaudière",
    category: "Handbags",
    subcategory: "Evening Clutches",
    price: 1299,
    oldPrice: null,
    badge: "sale",
    rating: "4.7",
    reviews: 193,
    sizes: ["One Size"],
    desc: "Architecture in your hands. A sleek silver box clutch with refined chevron texture and a crystal-studded arch handle. Minimalist glamour at its finest.",
    materials: "Metal frame with chevron texture, crystal handle embellishments, silk lining.",
    img: WA + "WhatsApp Image 2026-04-06 at 03.13.00.jpeg",
    images: [
      WA + "WhatsApp Image 2026-04-06 at 03.13.00.jpeg",
      WA + "WhatsApp Image 2026-04-06 at 03.12.57.jpeg"
    ]
  },

  // ── JEWELLERY SETS ──
  {
    id: 201,
    name: "Lumière Gold Set",
    category: "Jewellery",
    subcategory: "Full Sets",
    price: 600,
    oldPrice: null,
    badge: "bestseller",
    rating: "5.0",
    reviews: 914,
    sizes: ["One Size"],
    desc: "Radiant 18k gold-plated set featuring a graduated tennis bracelet, matching drop earrings and a delicate pendant necklace. Gift-ready in a luxe presentation box.",
    materials: "18k Gold plating, freshwater pearl accents, sterling silver base.",
    includes: ["Necklace (45cm)", "Bracelet (19cm)", "Earrings (Drop)"],
    img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.22 (2).jpeg",
  },
  {
    id: 202,
    name: "Noir Pearl Statement Set",
    category: "Jewellery",
    subcategory: "Full Sets",
    price: 700,
    oldPrice: null,
    badge: "new",
    rating: "4.9",
    reviews: 347,
    sizes: ["One Size"],
    desc: "Dramatic black-japanned metal meets lustrous akoya pearls. A modern contrast set that commands attention — earrings, necklace and ring.",
    materials: "Black-finished metal alloy, genuine akoya pearls, rhodium accents.",
    includes: ["Necklace (40cm + 5cm ext)", "Drop Earrings", "Cocktail Ring"],
    img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.21.jpeg",
  },
  {
    id: 203,
    name: "Ivory Bridal Collection",
    category: "Jewellery",
    subcategory: "Bridal Sets",
    price: 700,
    oldPrice: null,
    badge: "exclusive",
    rating: "5.0",
    reviews: 221,
    sizes: ["Ring: 5", "Ring: 6", "Ring: 7", "Ring: 8"],
    desc: "Designed for your most precious moments. This complete bridal set in white gold plating with cubic zirconia crystals evokes eternal elegance.",
    materials: "White gold plating, AAA cubic zirconia, sterling silver base.",
    includes: ["Tiara/Hair Comb", "Chandelier Earrings", "Tennis Necklace", "Bangle", "Ring"],
    img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.23.jpeg",
    images: ["Jewllery/WhatsApp Image 2026-04-06 at 13.30.23.jpeg", "Jewllery/WhatsApp Image 2026-04-06 at 13.30.24.jpeg"],
  },
  {
    id: 204,
    name: "Rose Golden Harmony Set",
    category: "Jewellery",
    subcategory: "Full Sets",
    price: 600,
    oldPrice: null,
    badge: "sale",
    rating: "4.8",
    reviews: 612,
    sizes: ["One Size"],
    desc: "Blush-toned rose gold with natural pink tourmaline. Feminine and romantic — perfect layering necklace with matching hoops.",
    materials: "Rose gold plating, pink tourmaline stones, sterling silver.",
    includes: ["Layered Necklace Set (2pc)", "Hoop Earrings", "Charm Bracelet"],
    img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.23 (1).jpeg",
  },
  {
    id: 205,
    name: "Onyx & Gold Minimalist Set",
    category: "Jewellery",
    subcategory: "Minimalist Sets",
    price: 600,
    oldPrice: null,
    badge: "new",
    rating: "4.7",
    reviews: 178,
    sizes: ["One Size"],
    desc: "For those who let elegance speak softly. Black onyx cabochons set in matte gold — refined, clean, and deeply chic.",
    materials: "Matte gold-plated brass, genuine black onyx.",
    includes: ["Bar Necklace", "Stud Earrings", "Cuff Bracelet"],
    img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.22.jpeg",
  },
  {
    id: 206,
    name: "Caramel Tortoise Shell Set",
    category: "Jewellery",
    subcategory: "Statement Sets",
    price: 700,
    oldPrice: null,
    badge: "hot",
    rating: "4.9",
    reviews: 445,
    sizes: ["One Size"],
    desc: "Bold warm-toned tortoiseshell resin meets brushed gold — this statement set adds instant warmth and personality to any outfit.",
    materials: "Resin, brushed gold-finish metal.",
    includes: ["Statement Necklace", "Large Hoop Earrings", "Stack Rings x3"],
    img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.22 (1).jpeg",
  },
];

const TRENDING = [
  { rank: 1, name: "Pochi Monogram Baguette", category: "Handbags", price: "₹1,299", id: 101, img: "Handbags.png" },
  { rank: 2, name: "Aquatic Kiss", category: "Perfumes", price: "From ₹500", id: 1, img: "Perfume image.png" },
  { rank: 3, name: "Lumière Gold Set", category: "Jewellery", price: "₹600", id: 201, img: "Jewllery/WhatsApp Image 2026-04-06 at 13.30.22 (2).jpeg" },
  { rank: 4, name: "Noir Quilted Chain Bag", category: "Handbags", price: "₹1,299", id: 103, img: "handbag 2.png" },
];
